exclude: "\\.snap$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]

  # python

  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.4.1
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

  # Terraform
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: tflint
      - id: shellcheck
      - id: terraform-fmt

  # sql formatter
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.5
    hooks:
      # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
      - id: sqlfluff-lint
        args: [--exclude-rules, "L008,L011,L031",
              --dialect, "clickhouse",
        ]
